language: node_js
node_js:
- 5.8.0
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  matrix:
  - secure: EFwnmiMg3+GUYl5lb2SQ5rbdfaV75XAW7WWmeM6K0Ezo7lYeeOKh++M+w5wNGAjlGi2XvRDGctQjF4pgV8uI+BanJSBb0/CIHt2AztYZAzAAGv4HkLnWTXKIhTYSJ33TNgUusW/EQCO2rkbaNoF00lP3cj4ySHIsLZbDGxyh+QYJkhnx9EfF5glIiB45cYtn7Je/qib6Mm0tX81YF07JD2pE/HkazvWLEJBhJ4YDOWj3NMg5xss5LwxBHAejVX8hof9Cgqz5OvDdF2p8+tu0rf7KdlKKyTP9r8DJTEgLASSbbWiugTYtunY0O6VWYBx4XScTgFdDsfqJvRI7R5k9zLX40GjUt3q+P4fGsCPvGfxWv8ewQWRlOBbPBOR03UwjaHLQL5BnavlhbUN1AbWfJ82sOPzM/X0+/5fDbbK1rMbqziky+FIrsGz3hl8nlJ4uJtwG/pnAHmmPtxFApRmmjcH6ECS7Lmbnnt34QoX0I8RbU1jKMl/EQvDV/fycT2KLSjIun4KnNTApwAB9ypiA4gJR+maEJKRZ6t5f42OujqI/Dg4jL+BCAGZgUPLmLujs1Q4NH0lIHI1Hlkh3MBONVsQY6DKPyTWxuZJZ1FA2v7/1GwnmOgrNQBkhUb6mUs6Gfy7Z8HXIAe6NELqr4/CrsFE/qxErxX0fSI0O61S+y2k=
  - secure: dy+2ssDvxMrGHOgrrj1ddnJI5mUPx9R6+5IxqoJ2BLArCgvTVyWxoqa+4c/xOTak4KwNoZ7V/yV9bPWpmawmYkBXFU9aX4MPnpR21HDiU99oe0PPFUZcQHxJmbMMNijfyDzsi8dMKEpHxyrPlyzRAYRHe3szUi1tmSBT4+qSHMP7lB9sZsbH7Ds+bp7e53au6Z6YUwt5kuMUUCA1vRh25DDJcNRN1o79EDdkWSAYPE0ASHl3SQb46uae4mTYPcbUeUvIOu+qahpueSorjVR471IKSfM89pzxGB4Gfgo90jQPc3bxemGxBZkf4p60V0DCJ4iqCDdQuQCVG1DASoHfbzpn1YIiQ/rIUvUaHYkk2OKdN4uU+TYPN2MCr2R2Eso86PJfuTvlqoOc3fwi8G4FlnXppZVVwe2V7sAtBHymqRzdFAH7Y3aOET7bewbxaHxEV9pEtbGK5O4kvbDWS4kh5fu0g6oIcYJuhh/MWdRK0G8VZwCRlslI63S5OVLvzvlxlx/THCyB0nJGgr9k4B11xwOTrl33Tw7GRRBmxK29srM0BkZ2n7I+ekXn3hfae5Oo23rbYL5ZMPAVAJJWKMiMUk+wLFLeUXbrYtM36nMUvWBaPzwzebIOmQeaVVkX2JTFySEmM5gMBel7sY7u2JW7DfmCa8H3ouU8UElPZLTc+6w=
script:
- npm run test
after_success:
- "./node_modules/.bin/coveralls --token=$CODECOV_TOKEN"
