// flow-typed signature: cf87449673967dc2659b9d81d9510835
// flow-typed version: <<STUB>>/rio_v^2.4.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rio/lib/config' {
  declare module.exports: any;
}

declare module 'rio/lib/crypt' {
  declare module.exports: any;
}

declare module 'rio/lib/evaluate-defer' {
  declare module.exports: any;
}

declare module 'rio/lib/evaluate' {
  declare module.exports: any;
}

declare module 'rio/lib/main' {
  declare module.exports: any;
}

declare module 'rio/lib/parse-sexp' {
  declare module.exports: any;
}

declare module 'rio/lib/parse-util' {
  declare module.exports: any;
}

declare module 'rio/lib/rio' {
  declare module.exports: any;
}

declare module 'rio/lib/shutdown' {
  declare module.exports: any;
}

declare module 'rio/lib/trace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rio/index' {
  declare module.exports: $Exports<'rio'>;
}
declare module 'rio/index.js' {
  declare module.exports: $Exports<'rio'>;
}
declare module 'rio/lib/config.js' {
  declare module.exports: $Exports<'rio/lib/config'>;
}
declare module 'rio/lib/crypt.js' {
  declare module.exports: $Exports<'rio/lib/crypt'>;
}
declare module 'rio/lib/evaluate-defer.js' {
  declare module.exports: $Exports<'rio/lib/evaluate-defer'>;
}
declare module 'rio/lib/evaluate.js' {
  declare module.exports: $Exports<'rio/lib/evaluate'>;
}
declare module 'rio/lib/main.js' {
  declare module.exports: $Exports<'rio/lib/main'>;
}
declare module 'rio/lib/parse-sexp.js' {
  declare module.exports: $Exports<'rio/lib/parse-sexp'>;
}
declare module 'rio/lib/parse-util.js' {
  declare module.exports: $Exports<'rio/lib/parse-util'>;
}
declare module 'rio/lib/rio.js' {
  declare module.exports: $Exports<'rio/lib/rio'>;
}
declare module 'rio/lib/shutdown.js' {
  declare module.exports: $Exports<'rio/lib/shutdown'>;
}
declare module 'rio/lib/trace.js' {
  declare module.exports: $Exports<'rio/lib/trace'>;
}
