// flow-typed signature: 0c286db1a7e1f0573c189e68e2f6bce3
// flow-typed version: <<STUB>>/topojson_v^3.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'topojson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'topojson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'topojson/dist/topojson' {
  declare module.exports: any;
}

declare module 'topojson/dist/topojson.min' {
  declare module.exports: any;
}

declare module 'topojson/dist/topojson.node' {
  declare module.exports: any;
}

declare module 'topojson/rollup.config' {
  declare module.exports: any;
}

declare module 'topojson/rollup.node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'topojson/dist/topojson.js' {
  declare module.exports: $Exports<'topojson/dist/topojson'>;
}
declare module 'topojson/dist/topojson.min.js' {
  declare module.exports: $Exports<'topojson/dist/topojson.min'>;
}
declare module 'topojson/dist/topojson.node.js' {
  declare module.exports: $Exports<'topojson/dist/topojson.node'>;
}
declare module 'topojson/index' {
  declare module.exports: $Exports<'topojson'>;
}
declare module 'topojson/index.js' {
  declare module.exports: $Exports<'topojson'>;
}
declare module 'topojson/rollup.config.js' {
  declare module.exports: $Exports<'topojson/rollup.config'>;
}
declare module 'topojson/rollup.node.js' {
  declare module.exports: $Exports<'topojson/rollup.node'>;
}
